#!/usr/bin/env node
'use strict';
// Speed Ecom Extension - build script.
//
// Reads the three PRISTINE marketplace extensions and generates dist/. The
// originals in Amazon/, Meesho/ and Myntra/ are never modified - they stay the
// source of truth, so when one of them is updated you re-run this instead of
// hand-merging again.
//
// Every transform below is mechanical, and each one is asserted. If an
// assumption stops holding (a marketplace renames a file, changes a rule ID,
// drops the importScripts line) the build fails loudly rather than silently
// producing a broken extension.
//
//   Usage:  node build.js

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = __dirname;
const SHELL = path.join(ROOT, 'shell');
const DIST = path.join(ROOT, 'dist');

let failures = 0;
function assert(cond, msg) {
  if (cond) return true;
  console.error(`  ✗ ASSERT FAILED: ${msg}`);
  failures++;
  return false;
}
function count(hay, needle) {
  return hay.split(needle).length - 1;
}

// ── Marketplace definitions ───────────────────────────────────────────────────
// prefixedKeys: storage keys that genuinely COLLIDE between marketplaces and so
// get namespaced by the shim. Deliberately minimal - `auth` is NOT listed, so
// the Speed Ecom login stays shared across all three panels (decided in
// MERGE_PLAN.md T4). Marketplace-unique keys (orderJob, downloadHistory, ...)
// are left alone so existing stored state survives the upgrade.
const MARKETS = [
  {
    id: 'amazon',
    mkt: 'amz',
    src: 'Amazon',
    prefixedKeys: ['syncProgress', 'syncLog'],
    ruleIds: [{ name: 'AUTH_HEADER_RULE_ID', from: 1, to: 101 }],
  },
  {
    id: 'meesho',
    mkt: 'mee',
    src: 'Meesho',
    prefixedKeys: [],
    ruleIds: [{ name: 'AUTH_HEADER_RULE_ID', from: 1, to: 201 }],
  },
  {
    id: 'myntra',
    mkt: 'myn',
    src: path.join('Myntra', 'Myntra'),
    prefixedKeys: ['syncProgress', 'syncLog'],
    ruleIds: [
      { name: 'CORS_FIX_RULE_ID', from: 1, to: 301 },
      { name: 'AUTH_HEADER_RULE_ID', from: 2, to: 302 },
    ],
  },
];

const JSZIP_IMPORT = "importScripts('jszip.min.js');\n";
const POPUP_SCRIPT_TAG = '<script src="popup.js"></script>';

// ── T1: IIFE wrap ─────────────────────────────────────────────────────────────
// Wraps a file's ORIGINAL body verbatim in an IIFE whose first statements are
// the strict-mode directive and a `chrome` binding that shadows the global one.
// Function-scoping the body is what makes ~40 duplicate top-level identifiers
// (TAG, sleep, authLogin, AUTH_ORIGIN, encryptPassword, ...) coexist in one
// service worker instead of throwing "Identifier 'TAG' has already been
// declared" and killing the whole worker.
//
// The directive is emitted BY US as the first statement: the originals' own
// 'use strict' would become a no-op once preceded by the chrome binding, so
// hoisting it here is what preserves strict mode.
function wrapIIFE(body, market, label) {
  const keys = JSON.stringify(market.prefixedKeys);
  return (
    `// ${label} - generated by build.js from ${market.src}. Do not edit.\n` +
    `// Body below is the original file, verbatim.\n` +
    `(function () {\n` +
    `'use strict';\n` +
    `const chrome = globalThis.__seShim(${JSON.stringify(market.mkt)}, ${keys});\n` +
    `\n` +
    body +
    `\n})();\n`
  );
}

// ── Build ─────────────────────────────────────────────────────────────────────
console.log('Speed Ecom Extension - build\n');

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

// --- Shared assets: verify identical across all three, then ship one copy ----
console.log('Shared assets');
const jszips = MARKETS.map((m) => fs.readFileSync(path.join(ROOT, m.src, 'jszip.min.js')));
const jszipHash = crypto.createHash('md5').update(jszips[0]).digest('hex');
assert(
  jszips.every((b) => b.equals(jszips[0])),
  'jszip.min.js differs between marketplaces - cannot ship a single copy'
);
fs.writeFileSync(path.join(DIST, 'jszip.min.js'), jszips[0]);
console.log(`  jszip.min.js       one copy (md5 ${jszipHash.slice(0, 8)})`);

const iconSets = MARKETS.map((m) => path.join(ROOT, m.src, 'icons'));
const iconNames = fs.readdirSync(iconSets[0]).sort();
for (const name of iconNames) {
  const bufs = iconSets.map((d) => fs.readFileSync(path.join(d, name)));
  assert(bufs.every((b) => b.equals(bufs[0])), `icons/${name} differs between marketplaces`);
}
fs.mkdirSync(path.join(DIST, 'icons'), { recursive: true });
for (const name of iconNames) {
  fs.copyFileSync(path.join(iconSets[0], name), path.join(DIST, 'icons', name));
}
fs.copyFileSync(path.join(ROOT, MARKETS[0].src, 'icon.png'), path.join(DIST, 'icon.png'));
console.log(`  icons/             one set (${iconNames.join(', ')})`);

// --- Per-marketplace ---------------------------------------------------------
for (const m of MARKETS) {
  console.log(`\n${m.id}  (from ${m.src}/)`);
  const srcDir = path.join(ROOT, m.src);
  const read = (f) => fs.readFileSync(path.join(srcDir, f), 'utf8');

  // content.js - VERBATIM. The three domains are disjoint, so the merged
  // manifest just declares three separate content_scripts entries.
  const content = read('content.js');
  fs.writeFileSync(path.join(DIST, `${m.id}_content.js`), content);
  console.log(`  ${m.id}_content.js`.padEnd(24) + 'verbatim');

  // background.js - T1 + T2.
  let bg = read('background.js');
  const bgOriginal = bg;

  assert(
    count(bg, JSZIP_IMPORT) === 1,
    `${m.src}/background.js: expected exactly 1 "${JSZIP_IMPORT.trim()}" line`
  );
  bg = bg.replace(JSZIP_IMPORT, ''); // entry loads jszip once for all three

  for (const r of m.ruleIds) {
    const from = `const ${r.name} = ${r.from};`;
    const to = `const ${r.name} = ${r.to};`;
    assert(count(bg, from) === 1, `${m.src}/background.js: expected exactly 1 "${from}"`);
    bg = bg.replace(from, to);
    // Every add/remove site must reference the constant, never a bare literal,
    // otherwise offsetting the constant would not actually move the rule.
    assert(
      !/(?:removeRuleIds|addRules)[\s\S]{0,80}?\bid:\s*\d/.test(bg),
      `${m.src}/background.js: found a literal DNR rule id near ${r.name}`
    );
  }

  const bgBody = bg;
  fs.writeFileSync(path.join(DIST, `${m.id}_background.js`), wrapIIFE(bgBody, m, `${m.id}_background.js`));

  // Independently reconstruct the expected body from the pristine original by
  // replaying only the declared transforms. Any other drift fails the build.
  let expected = bgOriginal.replace(JSZIP_IMPORT, '');
  for (const r of m.ruleIds) {
    expected = expected.replace(`const ${r.name} = ${r.from};`, `const ${r.name} = ${r.to};`);
  }
  assert(
    bgBody === expected,
    `${m.id}_background.js body diverged from original beyond the declared transforms`
  );
  const ruleList = m.ruleIds.map((r) => `${r.name} ${r.from}→${r.to}`).join(', ');
  console.log(`  ${m.id}_background.js`.padEnd(24) + `IIFE-wrapped, jszip import hoisted, ${ruleList}`);

  // popup.js - T1 only. Body is byte-identical to the original.
  const popupJs = read('popup.js');
  fs.writeFileSync(path.join(DIST, `${m.id}_popup.js`), wrapIIFE(popupJs, m, `${m.id}_popup.js`));
  const keyNote = m.prefixedKeys.length ? `shim namespaces ${m.prefixedKeys.join(', ')}` : 'no key collisions';
  console.log(`  ${m.id}_popup.js`.padEnd(24) + `IIFE-wrapped (body byte-identical), ${keyNote}`);

  // popup.html - VERBATIM except the one <script src>, which becomes:
  //   se_shim.js       -> the namespacing chrome facade (must load first)
  //   <mkt>_popup.js   -> the marketplace's own script, unchanged
  //   panel_chrome.js  -> Speed Ecom shell: back button, hides the panel's own
  //                       login/logout now that both are centralised on the
  //                       marketplace list (must load last, it adjusts the DOM
  //                       the marketplace script has just wired up)
  let popupHtml = read('popup.html');
  assert(
    count(popupHtml, POPUP_SCRIPT_TAG) === 1,
    `${m.src}/popup.html: expected exactly 1 ${POPUP_SCRIPT_TAG}`
  );
  // The panel chrome targets these three ids, so a marketplace dropping or
  // renaming one has to fail the build rather than silently lose the button.
  for (const id of ['userBar', 'logoutBtn', 'loginView']) {
    assert(
      popupHtml.includes(`id="${id}"`),
      `${m.src}/popup.html: expected id="${id}" (panel_chrome.js targets it)`
    );
  }
  const REPLACEMENT =
    `<script src="se_shim.js"></script>\n` +
    `  <script src="${m.id}_popup.js"></script>\n` +
    `  <script src="panel_chrome.js"></script>`;
  const before = popupHtml;
  popupHtml = popupHtml.replace(POPUP_SCRIPT_TAG, REPLACEMENT);
  assert(
    before.replace(POPUP_SCRIPT_TAG, '') === popupHtml.replace(REPLACEMENT, ''),
    `${m.src}/popup.html: markup changed beyond the script tag`
  );
  fs.writeFileSync(path.join(DIST, `${m.id}_popup.html`), popupHtml);
  console.log(`  ${m.id}_popup.html`.padEnd(24) + 'verbatim (script src rewritten)');
}

// --- Shell files -------------------------------------------------------------
console.log('\nShell');
for (const f of ['se_shim.js', 'router.js', 'panel_chrome.js', 'chooser.html', 'chooser.js']) {
  fs.copyFileSync(path.join(SHELL, f), path.join(DIST, f));
  console.log(`  ${f}`.padEnd(26) + 'copied');
}

// --- Service worker entry ----------------------------------------------------
// importScripts() is synchronous, so ordering is guaranteed: the shim must
// exist before any wrapped background calls __seShim, and JSZip must be on the
// global before any of them use it.
const entry = `'use strict';
// Speed Ecom Extension - service worker entry. Generated by build.js.
//
// MV3 allows exactly one service worker, so the three marketplace backgrounds
// are loaded here side by side. Each is wrapped in its own IIFE (see build.js)
// and therefore keeps its own private scope - no code is shared between them.

importScripts('se_shim.js');
importScripts('jszip.min.js');

importScripts(
${MARKETS.map((m) => `  '${m.id}_background.js'`).join(',\n')}
);

importScripts('router.js');

console.log('[speedecom] service worker ready:${MARKETS.map((m) => ` ${m.id}`).join('')}');
`;
fs.writeFileSync(path.join(DIST, 'background.js'), entry);
console.log('  background.js'.padEnd(26) + 'generated (entry)');

// --- Manifest ----------------------------------------------------------------
const srcManifests = MARKETS.map((m) => JSON.parse(fs.readFileSync(path.join(ROOT, m.src, 'manifest.json'), 'utf8')));

const permissions = [...new Set(srcManifests.flatMap((x) => x.permissions))].sort();
if (!permissions.includes('tabs')) permissions.push('tabs'); // router reads tab URLs
const hostPermissions = [...new Set(srcManifests.flatMap((x) => x.host_permissions))].sort();

const contentScripts = MARKETS.map((m, i) => ({
  matches: srcManifests[i].content_scripts[0].matches,
  js: [`${m.id}_content.js`],
  run_at: srcManifests[i].content_scripts[0].run_at,
}));

const icons = { 16: 'icons/icon16.png', 32: 'icons/icon32.png', 48: 'icons/icon48.png', 128: 'icons/icon128.png' };

const manifest = {
  manifest_version: 3,
  name: 'Speed Ecom Extension',
  version: '1.0.0',
  description:
    'Bulk-download Amazon, Meesho and Myntra seller reports. Opens the right panel automatically for whichever marketplace you are on.',
  permissions,
  host_permissions: hostPermissions,
  background: { service_worker: 'background.js' },
  icons,
  action: { default_popup: 'chooser.html', default_title: 'Speed Ecom', default_icon: icons },
  content_scripts: contentScripts,
};
fs.writeFileSync(path.join(DIST, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log('  manifest.json'.padEnd(26) + `generated (${permissions.length} permissions, ${hostPermissions.length} hosts)`);

// --- Post-build checks -------------------------------------------------------
console.log('\nChecks');

// Every content script's matches must survive unchanged from its origin.
for (let i = 0; i < MARKETS.length; i++) {
  const a = JSON.stringify(srcManifests[i].content_scripts[0].matches);
  const b = JSON.stringify(contentScripts[i].matches);
  assert(a === b, `${MARKETS[i].id}: content_scripts matches changed`);
}
console.log('  content_scripts matches preserved for all three');

// Host permissions must be a strict superset of each original.
for (let i = 0; i < MARKETS.length; i++) {
  const missing = srcManifests[i].host_permissions.filter((h) => !hostPermissions.includes(h));
  assert(missing.length === 0, `${MARKETS[i].id}: host permissions dropped: ${missing.join(', ')}`);
}
console.log('  host_permissions cover all three originals');

// DNR rule ids must be globally unique across the merged extension.
const allRuleIds = MARKETS.flatMap((m) => m.ruleIds.map((r) => r.to));
assert(new Set(allRuleIds).size === allRuleIds.length, `duplicate DNR rule ids: ${allRuleIds}`);
console.log(`  DNR rule ids unique: ${allRuleIds.join(', ')}`);

// Content scripts must stay byte-identical to their originals.
for (const m of MARKETS) {
  const a = fs.readFileSync(path.join(ROOT, m.src, 'content.js'));
  const b = fs.readFileSync(path.join(DIST, `${m.id}_content.js`));
  assert(a.equals(b), `${m.id}_content.js is not byte-identical to its original`);
}
console.log('  content scripts byte-identical to originals');

// Each wrapped popup body must still contain the original file verbatim.
for (const m of MARKETS) {
  const orig = fs.readFileSync(path.join(ROOT, m.src, 'popup.js'), 'utf8');
  const out = fs.readFileSync(path.join(DIST, `${m.id}_popup.js`), 'utf8');
  assert(out.includes(orig), `${m.id}_popup.js does not contain its original body verbatim`);
}
console.log('  popup bodies contained verbatim in wrappers');

console.log(
  failures === 0
    ? `\n✓ Build OK -> ${path.relative(process.cwd(), DIST)}\n`
    : `\n✗ Build finished with ${failures} failed assertion(s)\n`
);
process.exit(failures === 0 ? 0 : 1);
